{
	"jit: lsh, rsh, arsh by 1",
	.insns = {
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_MOV64_IMM(BPF_REG_1, 0xff),
	BPF_ALU64_IMM(BPF_LSH, BPF_REG_1, 1),
	BPF_ALU32_IMM(BPF_LSH, BPF_REG_1, 1),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_1, 0x3fc, 1),
	BPF_EXIT_INSN(),
	BPF_ALU64_IMM(BPF_RSH, BPF_REG_1, 1),
	BPF_ALU32_IMM(BPF_RSH, BPF_REG_1, 1),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_1, 0xff, 1),
	BPF_EXIT_INSN(),
	BPF_ALU64_IMM(BPF_ARSH, BPF_REG_1, 1),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_1, 0x7f, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: lsh, rsh, arsh by reg",
	.insns = {
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_MOV64_IMM(BPF_REG_4, 1),
	BPF_MOV64_IMM(BPF_REG_1, 0xff),
	BPF_ALU64_REG(BPF_LSH, BPF_REG_1, BPF_REG_0),
	BPF_ALU32_REG(BPF_LSH, BPF_REG_1, BPF_REG_4),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_1, 0x3fc, 1),
	BPF_EXIT_INSN(),
	BPF_ALU64_REG(BPF_RSH, BPF_REG_1, BPF_REG_4),
	BPF_MOV64_REG(BPF_REG_4, BPF_REG_1),
	BPF_ALU32_REG(BPF_RSH, BPF_REG_4, BPF_REG_0),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_4, 0xff, 1),
	BPF_EXIT_INSN(),
	BPF_ALU64_REG(BPF_ARSH, BPF_REG_4, BPF_REG_4),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_4, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: mov32 for ldimm64, 1",
	.insns = {
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_LD_IMM64(BPF_REG_1, 0xfeffffffffffffffULL),
	BPF_ALU64_IMM(BPF_RSH, BPF_REG_1, 32),
	BPF_LD_IMM64(BPF_REG_2, 0xfeffffffULL),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_1, BPF_REG_2, 1),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: mov32 for ldimm64, 2",
	.insns = {
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_LD_IMM64(BPF_REG_1, 0x1ffffffffULL),
	BPF_LD_IMM64(BPF_REG_2, 0xffffffffULL),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_1, BPF_REG_2, 1),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: various mul tests",
	.insns = {
	BPF_LD_IMM64(BPF_REG_2, 0xeeff0d413122ULL),
	BPF_LD_IMM64(BPF_REG_0, 0xfefefeULL),
	BPF_LD_IMM64(BPF_REG_1, 0xefefefULL),
	BPF_ALU64_REG(BPF_MUL, BPF_REG_0, BPF_REG_1),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_0, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_3, 0xfefefeULL),
	BPF_ALU64_REG(BPF_MUL, BPF_REG_3, BPF_REG_1),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_3, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_3, 0xfefefeULL),
	BPF_ALU64_IMM(BPF_MUL, BPF_REG_3, 0xefefef),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_3, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV32_REG(BPF_REG_2, BPF_REG_2),
	BPF_LD_IMM64(BPF_REG_0, 0xfefefeULL),
	BPF_ALU32_REG(BPF_MUL, BPF_REG_0, BPF_REG_1),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_0, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_3, 0xfefefeULL),
	BPF_ALU32_REG(BPF_MUL, BPF_REG_3, BPF_REG_1),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_3, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_3, 0xfefefeULL),
	BPF_ALU32_IMM(BPF_MUL, BPF_REG_3, 0xefefef),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_3, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_0, 0xfefefeULL),
	BPF_LD_IMM64(BPF_REG_2, 0x2ad4d4aaULL),
	BPF_ALU32_IMM(BPF_MUL, BPF_REG_0, 0x2b),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_0, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_0, 0x952a7bbcULL),
	BPF_LD_IMM64(BPF_REG_1, 0xfefefeULL),
	BPF_LD_IMM64(BPF_REG_5, 0xeeff0d413122ULL),
	BPF_ALU32_REG(BPF_MUL, BPF_REG_5, BPF_REG_1),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_5, BPF_REG_0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: various div tests",
	.insns = {
	BPF_LD_IMM64(BPF_REG_2, 0xefeffeULL),
	BPF_LD_IMM64(BPF_REG_0, 0xeeff0d413122ULL),
	BPF_LD_IMM64(BPF_REG_1, 0xfefeeeULL),
	BPF_ALU64_REG(BPF_DIV, BPF_REG_0, BPF_REG_1),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_0, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_3, 0xeeff0d413122ULL),
	BPF_ALU64_IMM(BPF_DIV, BPF_REG_3, 0xfefeeeULL),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_3, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_2, 0xaa93ULL),
	BPF_ALU64_IMM(BPF_MOD, BPF_REG_1, 0xbeefULL),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_1, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_1, 0xfefeeeULL),
	BPF_LD_IMM64(BPF_REG_3, 0xbeefULL),
	BPF_ALU64_REG(BPF_MOD, BPF_REG_1, BPF_REG_3),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_1, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_LD_IMM64(BPF_REG_2, 0x5ee1dULL),
	BPF_LD_IMM64(BPF_REG_1, 0xfefeeeULL),
	BPF_LD_IMM64(BPF_REG_3, 0x2bULL),
	BPF_ALU32_REG(BPF_DIV, BPF_REG_1, BPF_REG_3),
	BPF_JMP_REG(BPF_JEQ, BPF_REG_1, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_ALU32_REG(BPF_DIV, BPF_REG_1, BPF_REG_1),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_1, 1, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_ALU64_REG(BPF_MOD, BPF_REG_2, BPF_REG_2),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_2, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: jsgt, jslt",
	.insns = {
	BPF_LD_IMM64(BPF_REG_1, 0x80000000ULL),
	BPF_LD_IMM64(BPF_REG_2, 0x0ULL),
	BPF_JMP_REG(BPF_JSGT, BPF_REG_1, BPF_REG_2, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),

	BPF_JMP_REG(BPF_JSLT, BPF_REG_2, BPF_REG_1, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),

	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: torturous jumps, imm8 nop jmp and pure jump padding",
	.insns = { },
	.fill_helper = bpf_fill_torturous_jumps,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = ACCEPT,
	.retval = 1,
},
{
	"jit: torturous jumps, imm32 nop jmp and jmp_cond padding",
	.insns = { },
	.fill_helper = bpf_fill_torturous_jumps,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = ACCEPT,
	.retval = 2,
},
{
	"jit: torturous jumps in subprog",
	.insns = { },
	.fill_helper = bpf_fill_torturous_jumps,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = ACCEPT,
	.retval = 3,
},
{
	"jit: PROBE_MEM_READ ldx success cases",
	.insns = {
	/* int *reg_9 = fp - 12;
	 * *reg_9 = 0
	 */
	BPF_MOV64_REG(BPF_REG_9, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_9, -12),
	BPF_ST_MEM(BPF_W, BPF_REG_9, 0, 0),
	BPF_LD_MAP_FD(BPF_REG_6, 0),

	/* long *dummy_arg = fp - 8
	 * ret = bpf_kfunc_call_test_acquire(dummy_arg)
	 * if (!ret) exit
	 */
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -8),
	BPF_ST_MEM(BPF_DW, BPF_REG_1, 0, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, BPF_PSEUDO_KFUNC_CALL, 0, 0),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 5),
	BPF_EXIT_INSN(),

	/* label err_exit
	 * err_exit:
	 *  bpf_kfunc_call_test_release(reg_7);
	 *  return 1;
	 */
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_7),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, BPF_PSEUDO_KFUNC_CALL, 0, 0),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),

	/* reg_7 = acquired prog_test_ref_kfunc */
	BPF_MOV64_REG(BPF_REG_7, BPF_REG_0),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_6),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_9),

	/* ret = bpf_map_lookup_elem(&data, &zero);
	 * if (!ret) goto err_exit;
	 * else reg_0 = ptr_map_val containing struct prog_test_ref_kfunc
	 */
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_map_lookup_elem),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 0, -10),

	/* ret = bpf_kptr_xchg(ptr_map_val, acquired prog_test_ref_kfunc)
	 * if(ret) goto err_exit;
	 */
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_7),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_kptr_xchg),
	BPF_MOV64_REG(BPF_REG_7, BPF_REG_0),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, -15),

	/* Do a direct LD of the struct prog_test_ref_kfunc we just xchg'd into
	 * map
	 */
	BPF_LD_MAP_VALUE(BPF_REG_0, 0, 0),
	BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_0, 0),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),

	/* Try accessing its fields - this should trigger PROBE_MEM jit
	 * behavior
	 *
	 * r0 = prog_test_ref_kfunc.a * 2 + prog_test_ref_kfunc.b
	 */
	BPF_LDX_MEM(BPF_W, BPF_REG_1, BPF_REG_0, 0),
	BPF_LDX_MEM(BPF_W, BPF_REG_2, BPF_REG_0, 4),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_0, 8),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, -8),
	BPF_ALU64_REG(BPF_ADD, BPF_REG_0, BPF_REG_1),
	BPF_ALU64_REG(BPF_ADD, BPF_REG_0, BPF_REG_2),
	BPF_EXIT_INSN(),
	},
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.fixup_map_probe_mem_read = { 3, 26 },
	.fixup_kfunc_btf_id = {
		{ "bpf_kfunc_call_test_acquire", 8 },
		{ "bpf_kfunc_call_test_release", 12},
	},
	.result = ACCEPT,
	.retval = 192,
},
